---
categories:
- ""
- ""
date: "2017-10-31T21:28:43-05:00"
description: ""
draft: false
image: ""
keywords: ""
slug: project2
title: Project II
---

<script src="/rmarkdown-libs/header-attrs/header-attrs.js"></script>


<div id="climate-change-and-temperature-anomalies" class="section level1">
<h1>1. Climate change and temperature anomalies</h1>
<p>If we wanted to study climate change, we can find data on the <em>Combined Land-Surface Air and Sea-Surface Water Temperature Anomalies</em> in the Northern Hemisphere at <a href="https://data.giss.nasa.gov/gistemp">NASA’s Goddard Institute for Space Studies</a>. The <a href="https://data.giss.nasa.gov/gistemp/tabledata_v4/NH.Ts+dSST.txt">tabular data of temperature anomalies can be found here</a></p>
<p>To define temperature anomalies, we need to have a reference, or base, period which NASA clearly states that it is the period between 1951-1980.</p>
<p>We run the code below to load the file:</p>
<pre class="r"><code>weather &lt;- 
  read_csv(&quot;https://data.giss.nasa.gov/gistemp/tabledata_v4/NH.Ts+dSST.csv&quot;, 
           skip = 1, 
           na = &quot;***&quot;)</code></pre>
<p>For each month and year, the dataframe shows the deviation of temperature from the normal (expected). Further the dataframe is in wide format.</p>
<p>We have two objectives in this section:</p>
<ol style="list-style-type: decimal">
<li><p>We select the year and the twelve month variables from the <code>weather</code> dataset. We do not need the others (J-D, D-N, DJF, etc.) for this assignment.</p></li>
<li><p>We convert the dataframe from wide to ‘long’ format. We name the new dataframe as <code>tidyweather</code>, name the variable containing the name of the month as <code>month</code>, and the temperature deviation values as <code>delta</code>.</p></li>
</ol>
<pre class="r"><code>tidyweather &lt;- weather %&gt;% 
  select(-c(&quot;J-D&quot;,&quot;D-N&quot;,&quot;DJF&quot;,&quot;MAM&quot;,&quot;JJA&quot;,&quot;SON&quot;)) %&gt;% 
  pivot_longer(2:13,
               names_to = &quot;Month&quot;,
               values_to = &quot;delta&quot;)</code></pre>
<p>We inspect our dataframe. It has three variables now, one each for</p>
<ol style="list-style-type: decimal">
<li>year,</li>
<li>month, and</li>
<li>delta, or temperature deviation.</li>
</ol>
<div id="plotting-information" class="section level2">
<h2>1.1. Plotting Information</h2>
<p>Let us plot the data using a time-series scatter plot, and add a trendline. To do that, we first need to create a new variable called <code>date</code> in order to ensure that the <code>delta</code> values are plot chronologically.</p>
<pre class="r"><code>tidyweather &lt;- tidyweather %&gt;%
  mutate(date = ymd(paste(as.character(Year), Month, &quot;1&quot;)),
         month = month(date, label=TRUE),
         year = year(date))

ggplot(tidyweather, aes(x=date, y = delta))+
  geom_point()+
  geom_smooth(color=&quot;red&quot;) +
  theme_bw() +
  labs (
    title = &quot;Weather Anomalies&quot;
  )</code></pre>
<p><img src="/blogs/homework2_Group8_chuhan_files/figure-html/scatter_plot-1.png" width="648" style="display: block; margin: auto;" />
We use facet_wrap to see the weather anomalies by month of the year.</p>
<p><img src="/blogs/homework2_Group8_chuhan_files/figure-html/facet_wrap-1.png" width="648" style="display: block; margin: auto;" /></p>
<p>We remove data before 1800 and before using <code>filter</code>. Then, we use the <code>mutate</code> function to create a new variable <code>interval</code> which contains information on which period each observation belongs to.</p>
<pre class="r"><code>comparison &lt;- tidyweather %&gt;% 
  filter(Year&gt;= 1881) %&gt;%     #remove years prior to 1881
  #create new variable &#39;interval&#39;, and assign values based on criteria below:
  mutate(interval = case_when(
    Year %in% c(1881:1920) ~ &quot;1881-1920&quot;,
    Year %in% c(1921:1950) ~ &quot;1921-1950&quot;,
    Year %in% c(1951:1980) ~ &quot;1951-1980&quot;,
    Year %in% c(1981:2010) ~ &quot;1981-2010&quot;,
    TRUE ~ &quot;2011-present&quot;
  ))</code></pre>
<p>Now that we have the <code>interval</code> variable, we can create a density plot to study the distribution of monthly deviations (<code>delta</code>), grouped by the different time periods we are interested in.</p>
<pre class="r"><code>ggplot(comparison, aes(x=delta, fill=interval))+
  geom_density(alpha=0.2) +   #density plot with tranparency set to 20%
  theme_bw() +                #theme
  labs (
    title = &quot;Density Plot for Monthly Temperature Anomalies&quot;,
    y     = &quot;Density&quot;         #changing y-axis label to sentence case
  )</code></pre>
<p>So far, we have been working with monthly anomalies. However, we might be interested in average annual anomalies.</p>
<pre class="r"><code>#creating yearly averages
average_annual_anomaly &lt;- tidyweather %&gt;% 
  group_by(year) %&gt;%   #grouping data by Year
  
  # creating summaries for mean delta 
  # use `na.rm=TRUE` to eliminate NA (not available) values 
  summarise(annual_average_delta = mean(delta, na.rm=TRUE))

#plotting the data:
ggplot(average_annual_anomaly, aes(x=year, y= annual_average_delta))+
  geom_point()+
  
  #Fit the best fit line, using LOESS method
  geom_smooth() +
  
  #change to theme_bw() to have white background + black frame around plot
  theme_bw() +
  labs (
    title = &quot;Average Yearly Anomaly&quot;,
    y     = &quot;Average Annual Delta&quot;
  )                         </code></pre>
</div>
<div id="confidence-interval-for-delta" class="section level2">
<h2>1.2. Confidence Interval for <code>delta</code></h2>
<p><a href="https://earthobservatory.nasa.gov/world-of-change/decadaltemp.php">NASA points out on their website</a> that</p>
<blockquote>
<p>A one-degree global change is significant because it takes a vast amount of heat to warm all the oceans, atmosphere, and land by that much. In the past, a one- to two-degree drop was all it took to plunge the Earth into the Little Ice Age.</p>
</blockquote>
<p>We construct a confidence interval for the average annual delta since 2011, both using a formula and using a bootstrap simulation with the <code>infer</code> package.</p>
<pre class="r"><code>formula_ci &lt;- comparison %&gt;% 
  # choose the interval 2011-present
  # what dplyr verb will you use? 
  filter(year &gt;= 2011) %&gt;%
  
  # calculate summary statistics for temperature deviation (delta) 
  # calculate mean, SD, count, SE, lower/upper 95% CI
  # what dplyr verb will you use? 
  summarise(mean_delta = mean(delta, na.rm=TRUE),
            SD_delta = sd(delta, na.rm=TRUE),
            count_delta = n()) %&gt;% 
  mutate(SE_delta = SD_delta/sqrt(count_delta),
         lower_CI = mean_delta-2*SE_delta,
         upper_CI = mean_delta+2*SE_delta)

#print out formula_CI
formula_ci</code></pre>
<pre class="r"><code># use the infer package to construct a 95% CI for delta
set.seed(1234)

boot_weather &lt;- comparison %&gt;%
  # Choose only  Animation films
  filter(year &gt;= 2011) %&gt;%
  
  # Specify the variable of interest
  specify(response = delta) %&gt;%
  
  # Generate a bunch of bootstrap samples
  generate(reps = 1000, type = &quot;bootstrap&quot;) %&gt;%
  
  # Find the median of each sample
  calculate(stat = &quot;mean&quot;)

percentile_ci &lt;- boot_weather %&gt;% 
  get_confidence_interval(level = 0.95, type = &quot;percentile&quot;)
percentile_ci</code></pre>
<pre><code>## # A tibble: 1 x 2
##   lower_ci upper_ci
##      &lt;dbl&gt;    &lt;dbl&gt;
## 1     1.02     1.11</code></pre>
<p>The data shows us that from 2011 till present, the mean variation from expected temperature is positive 1.06 degree, the standard deviation is 0.276 and there are a total of 132 observations. With bootstrap, we generate a thousand sample means, each calculated with 132 observations extracted with replacement from our dataset, and get a new distribution representing the distribution of the population mean. With 95% confidence, we can say that the true population mean lays in the interval [1.01, 1.11].</p>
</div>
</div>
<div id="general-social-survey-gss" class="section level1">
<h1>2. General Social Survey (GSS)</h1>
<p>The <a href="http://www.gss.norc.org/">General Social Survey (GSS)</a> gathers data on American society in order to monitor and explain trends in attitudes, behaviours, and attributes. Many trends have been tracked for decades, so one can see the evolution of attitudes, etc in American Society.</p>
<p>We analyze data from the <strong>2016 GSS sample data</strong>, using it to estimate values of <em>population parameters</em> of interest about US adults. The GSS sample data file has 2867 observations of 935 variables, but we are only interested in very few of these variables and you are using a smaller file.</p>
<pre class="r"><code>gss &lt;- read_csv(here::here(&quot;data&quot;, &quot;smallgss2016.csv&quot;), 
                na = c(&quot;&quot;, &quot;Don&#39;t know&quot;,
                       &quot;No answer&quot;, &quot;Not applicable&quot;, &quot;NA&quot;))</code></pre>
<p>We create 95% confidence intervals for population parameters. The variables we have are the following:</p>
<ul>
<li>hours and minutes spent on email weekly. The responses to these questions are recorded in the <code>emailhr</code> and <code>emailmin</code> variables. For example, if the response is 2.50 hours, this would be recorded as emailhr = 2 and emailmin = 30.</li>
<li><code>snapchat</code>, <code>instagrm</code>, <code>twitter</code>: whether respondents used these social media in 2016</li>
<li><code>sex</code>: Female - Male</li>
<li><code>degree</code>: highest education level attained</li>
</ul>
<div id="instagram-and-snapchat-by-sex" class="section level2">
<h2>2.1. Instagram and Snapchat, by sex</h2>
<p>We estimate the <em>population</em> proportion of Snapchat or Instagram users in 2016.</p>
<ol style="list-style-type: decimal">
<li>We create a new variable, <code>snap_insta</code> that is <em>Yes</em> if the respondent reported using any of Snapchat (<code>snapchat</code>) or Instagram (<code>instagrm</code>), and <em>No</em> if not.</li>
</ol>
<pre class="r"><code>gss &lt;- gss %&gt;%  
  mutate(snap_insta = ifelse(snapchat == &quot;Yes&quot; | instagrm ==&quot;Yes&quot;, &quot;Yes&quot;, &quot;No&quot;))</code></pre>
<ol style="list-style-type: decimal">
<li>We calculate the proportion of Yes’s for <code>snap_insta</code> among those who answered the question, i.e. excluding NAs.</li>
</ol>
<pre class="r"><code>gss %&gt;% 
  select(snap_insta) %&gt;% 
  na.omit() %&gt;% 
  group_by(snap_insta) %&gt;%
  summarise(count_snap_insta = count(snap_insta)) %&gt;% 
  pivot_wider(names_from = snap_insta, values_from = count_snap_insta) %&gt;% 
  mutate(proportion = Yes/(No+Yes))</code></pre>
<pre><code>## # A tibble: 1 x 3
##      No   Yes proportion
##   &lt;int&gt; &lt;int&gt;      &lt;dbl&gt;
## 1   858   514      0.375</code></pre>
<ol style="list-style-type: decimal">
<li>Using the CI formula for proportions, we construct 95% CIs for men and women who used either Snapchat or Instagram</li>
</ol>
<pre class="r"><code>sex_snap_insta&lt;-gss %&gt;% 
  filter(snap_insta==&quot;Yes&quot;) %&gt;% 
  group_by(sex) %&gt;% 
  summarise(count_sex = count(sex))%&gt;% 
  pivot_wider(names_from = sex, values_from = count_sex) %&gt;% 
  mutate(count_all=Female+Male,Male_rate = Male/(Male+Female),
         Female_rate=1-Male_rate)
sex_snap_insta</code></pre>
<pre><code>## # A tibble: 1 x 5
##   Female  Male count_all Male_rate Female_rate
##    &lt;int&gt; &lt;int&gt;     &lt;int&gt;     &lt;dbl&gt;       &lt;dbl&gt;
## 1    322   192       514     0.374       0.626</code></pre>
<pre class="r"><code>#proportion test for Male
prop.test(192,514)</code></pre>
<pre><code>## 
##  1-sample proportions test with continuity correction
## 
## data:  192 out of 514
## X-squared = 32, df = 1, p-value = 1e-08
## alternative hypothesis: true p is not equal to 0.5
## 95 percent confidence interval:
##  0.332 0.417
## sample estimates:
##     p 
## 0.374</code></pre>
<pre class="r"><code>#proportion test for Female
prop.test(322,514)</code></pre>
<pre><code>## 
##  1-sample proportions test with continuity correction
## 
## data:  322 out of 514
## X-squared = 32, df = 1, p-value = 1e-08
## alternative hypothesis: true p is not equal to 0.5
## 95 percent confidence interval:
##  0.583 0.668
## sample estimates:
##     p 
## 0.626</code></pre>
</div>
<div id="twitter-by-education-level" class="section level2">
<h2>2.2. Twitter, by education level</h2>
<p>We estimate the <em>population</em> proportion of Twitter users by education level in 2016.</p>
<p>There are 5 education levels in variable <code>degree</code> which, in ascneding order of years of education, are Lt high school, High School, Junior college, Bachelor, Graduate.</p>
<ol style="list-style-type: decimal">
<li>We turn <code>degree</code> from a character variable into a factor variable.</li>
</ol>
<pre class="r"><code>gss$degree=factor(gss$degree,levels=c(&quot;Lt high school&quot;,&quot;High School&quot;,&quot;Junior college&quot;,&quot;Bachelor&quot;,&quot;Graduate&quot;))</code></pre>
<ol style="list-style-type: decimal">
<li>We create a new variable, <code>bachelor_graduate</code> that is <em>Yes</em> if the respondent has either a <code>Bachelor</code> or <code>Graduate</code> degree.</li>
</ol>
<pre class="r"><code>gss&lt;-gss %&gt;% 
  mutate(bachelor_graduate=ifelse(degree==&quot;Bachelor&quot;|degree==&quot;Graduate&quot;,&quot;yes&quot;,&quot;no&quot;))</code></pre>
<ol style="list-style-type: decimal">
<li>We calculate the proportion of <code>bachelor_graduate</code> who do (Yes) and who don’t (No) use twitter.</li>
</ol>
<pre class="r"><code>prop_twitter_yes&lt;-gss %&gt;% 
  filter(bachelor_graduate==&quot;yes&quot;) %&gt;% 
  select(twitter) %&gt;%
  na.omit() %&gt;% 
  summarize(yes_twitter_rate=count(twitter==&quot;Yes&quot;)/n(),
            no_twitter_rate=count(twitter==&quot;No&quot;)/n())
prop_twitter_yes</code></pre>
<pre><code>## # A tibble: 1 x 2
##   yes_twitter_rate no_twitter_rate
##              &lt;dbl&gt;           &lt;dbl&gt;
## 1            0.233           0.767</code></pre>
<pre class="r"><code>prop_twitter_yes&lt;-gss %&gt;% 
  group_by(bachelor_graduate) %&gt;% 
  select(twitter) %&gt;%
  na.omit() %&gt;% 
  summarize(yes_twitter=count(twitter==&quot;Yes&quot;),
            no_twitter=count(twitter==&quot;No&quot;),
            count_all=yes_twitter+no_twitter,
            yes_twitter_rate=count(twitter==&quot;Yes&quot;)/n(),
            no_twitter_rate=count(twitter==&quot;No&quot;)/n())
prop_twitter_yes</code></pre>
<pre><code>## # A tibble: 2 x 6
##   bachelor_graduate yes_twitter no_twitter count_all yes_twitter_rate
##   &lt;chr&gt;                   &lt;int&gt;      &lt;int&gt;     &lt;int&gt;            &lt;dbl&gt;
## 1 no                         30        173       203            0.148
## 2 yes                       114        375       489            0.233
## # ... with 1 more variable: no_twitter_rate &lt;dbl&gt;</code></pre>
<ol style="list-style-type: decimal">
<li>Using the CI formula for proportions, we construct two 95% CIs for <code>bachelor_graduate</code> vs whether they use (Yes) and don’t (No) use twitter.</li>
</ol>
<pre class="r"><code>prop.test(114,489)</code></pre>
<pre><code>## 
##  1-sample proportions test with continuity correction
## 
## data:  114 out of 489
## X-squared = 138, df = 1, p-value &lt;2e-16
## alternative hypothesis: true p is not equal to 0.5
## 95 percent confidence interval:
##  0.197 0.274
## sample estimates:
##     p 
## 0.233</code></pre>
<pre class="r"><code>prop.test(30,203)</code></pre>
<pre><code>## 
##  1-sample proportions test with continuity correction
## 
## data:  30 out of 203
## X-squared = 99, df = 1, p-value &lt;2e-16
## alternative hypothesis: true p is not equal to 0.5
## 95 percent confidence interval:
##  0.103 0.206
## sample estimates:
##     p 
## 0.148</code></pre>
<p>We note that these two confidence intervals overlap.</p>
</div>
<div id="email-usage" class="section level2">
<h2>2.3. Email usage</h2>
<p>Laslty, we estimate the <em>population</em> parameter on time spent on email weekly.</p>
<ol style="list-style-type: decimal">
<li>We create a new variable called <code>email</code> that combines <code>emailhr</code> and <code>emailmin</code> to reports the number of minutes the respondents spend on email weekly.</li>
</ol>
<pre class="r"><code>gss&lt;-gss %&gt;% 
  mutate(email=emailmin+emailhr*60)
head(gss)</code></pre>
<pre><code>## # A tibble: 6 x 10
##   emailmin emailhr snapchat instagrm twitter sex    degree         snap_insta
##      &lt;dbl&gt;   &lt;dbl&gt; &lt;chr&gt;    &lt;chr&gt;    &lt;chr&gt;   &lt;chr&gt;  &lt;fct&gt;          &lt;chr&gt;     
## 1        0      12 &lt;NA&gt;     &lt;NA&gt;     &lt;NA&gt;    Male   Bachelor       &lt;NA&gt;      
## 2       30       0 No       No       No      Male   &lt;NA&gt;           No        
## 3       NA      NA No       No       No      Male   Bachelor       No        
## 4       10       0 &lt;NA&gt;     &lt;NA&gt;     &lt;NA&gt;    Female &lt;NA&gt;           &lt;NA&gt;      
## 5       NA      NA Yes      Yes      No      Female Graduate       Yes       
## 6        0       2 No       Yes      No      Female Junior college Yes       
## # ... with 2 more variables: bachelor_graduate &lt;chr&gt;, email &lt;dbl&gt;</code></pre>
<ol style="list-style-type: decimal">
<li>We visualise the distribution of this new variable. We find the mean and the median number of minutes respondents spend on email weekly.</li>
</ol>
<pre class="r"><code>gss %&gt;% 
  select(email) %&gt;%
  na.omit() %&gt;% 
  ggplot(aes(x=email))+
  geom_histogram(bins=20)</code></pre>
<p><img src="/blogs/homework2_Group8_chuhan_files/figure-html/unnamed-chunk-10-1.png" width="648" style="display: block; margin: auto;" /></p>
<pre class="r"><code>gss_email&lt;-gss %&gt;% 
  select(email) %&gt;% 
  na.omit() %&gt;% 
  summarize(mean_email=mean(email),
            median_email=median(email))
gss_email</code></pre>
<pre><code>## # A tibble: 1 x 2
##   mean_email median_email
##        &lt;dbl&gt;        &lt;dbl&gt;
## 1       417.          120</code></pre>
<p>The histogram shows that the minutes Americans spend on email is right-skewed. In this case, the median will be a better measure of the minutes Americans spend on email than the mean.</p>
<ol style="list-style-type: decimal">
<li>Using the <code>infer</code> package, we calculate a 95% bootstrap confidence interval for the mean amount of time Americans spend on email weekly.</li>
</ol>
<pre class="r"><code>set.seed(1234)

boot_active2 &lt;- gss  %&gt;%
  select(email) %&gt;% 
  na.omit() %&gt;% 
  # Specify the variable of interest
  specify(response = email) %&gt;%
  
  # Generate a bunch of bootstrap samples
  generate(reps = 1000, type = &quot;bootstrap&quot;) %&gt;%
  
  # Find the median of each sample
  calculate(stat = &quot;mean&quot;)

percentile_ci &lt;- boot_active2 %&gt;% 
  get_confidence_interval(level = 0.95, type = &quot;percentile&quot;)
percentile_ci</code></pre>
<pre><code>## # A tibble: 1 x 2
##   lower_ci upper_ci
##      &lt;dbl&gt;    &lt;dbl&gt;
## 1     385.     453.</code></pre>
<p>The lower CI is 6 hours 25 minutes, the upper CI is 7 hours 33 minutes.</p>
<ol style="list-style-type: decimal">
<li>Do we expect a 99% confidence interval to be wider or narrower than the interval you calculated above?</li>
</ol>
<pre class="r"><code>set.seed(1234)
boot_active3 &lt;- gss  %&gt;%
  select(email) %&gt;% 
  na.omit() %&gt;% 
  # Specify the variable of interest
  specify(response = email) %&gt;%
  
  # Generate a bunch of bootstrap samples
  generate(reps = 1000, type = &quot;bootstrap&quot;) %&gt;%
  
  # Find the median of each sample
  calculate(stat = &quot;mean&quot;)

percentile_ci &lt;- boot_active3 %&gt;% 
  get_confidence_interval(level = 0.99, type = &quot;percentile&quot;)
percentile_ci</code></pre>
<pre><code>## # A tibble: 1 x 2
##   lower_ci upper_ci
##      &lt;dbl&gt;    &lt;dbl&gt;
## 1     375.     465.</code></pre>
<p>A 99% confidence interval will be wider, as we are more confident (compared to 95% confident) that the mean will locate in this interval, the interval should be wider.</p>
</div>
</div>
<div id="bidens-approval-margins" class="section level1">
<h1>3. Biden’s Approval Margins</h1>
<p>As we saw in class, fivethirtyeight.com has detailed data on <a href="https://projects.fivethirtyeight.com/biden-approval-ratings">all polls that track the president’s approval</a></p>
<pre class="r"><code># Import approval polls data directly off fivethirtyeight website
approval_polllist &lt;- read_csv(&#39;https://projects.fivethirtyeight.com/biden-approval-data/approval_polllist.csv&#39;) 


glimpse(approval_polllist) </code></pre>
<pre><code>## Rows: 1,600
## Columns: 22
## $ president           &lt;chr&gt; &quot;Joseph R. Biden Jr.&quot;, &quot;Joseph R. Biden Jr.&quot;, &quot;Jos~
## $ subgroup            &lt;chr&gt; &quot;All polls&quot;, &quot;All polls&quot;, &quot;All polls&quot;, &quot;All polls&quot;~
## $ modeldate           &lt;chr&gt; &quot;9/17/2021&quot;, &quot;9/17/2021&quot;, &quot;9/17/2021&quot;, &quot;9/17/2021&quot;~
## $ startdate           &lt;chr&gt; &quot;1/31/2021&quot;, &quot;2/1/2021&quot;, &quot;2/1/2021&quot;, &quot;2/2/2021&quot;, &quot;~
## $ enddate             &lt;chr&gt; &quot;2/2/2021&quot;, &quot;2/3/2021&quot;, &quot;2/3/2021&quot;, &quot;2/4/2021&quot;, &quot;2~
## $ pollster            &lt;chr&gt; &quot;YouGov&quot;, &quot;Rasmussen Reports/Pulse Opinion Researc~
## $ grade               &lt;chr&gt; &quot;B+&quot;, &quot;B&quot;, &quot;B&quot;, &quot;B&quot;, &quot;B&quot;, &quot;B-&quot;, &quot;A-&quot;, &quot;B&quot;, &quot;B-&quot;, &quot;~
## $ samplesize          &lt;dbl&gt; 1500, 1500, 15000, 1500, 15000, 1005, 1429, 15000,~
## $ population          &lt;chr&gt; &quot;a&quot;, &quot;lv&quot;, &quot;a&quot;, &quot;lv&quot;, &quot;a&quot;, &quot;a&quot;, &quot;a&quot;, &quot;a&quot;, &quot;rv&quot;, &quot;l~
## $ weight              &lt;dbl&gt; 1.0856, 0.3308, 0.2786, 0.3086, 0.2507, 0.8741, 2.~
## $ influence           &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,~
## $ approve             &lt;dbl&gt; 46, 52, 54, 49, 54, 57, 49, 54, 60, 50, 54, 55, 51~
## $ disapprove          &lt;dbl&gt; 38, 46, 33, 48, 34, 34, 39, 34, 32, 47, 34, 33, 46~
## $ adjusted_approve    &lt;dbl&gt; 47.2, 54.4, 52.5, 51.4, 52.5, 55.9, 49.6, 52.5, 59~
## $ adjusted_disapprove &lt;dbl&gt; 38.3, 40.1, 36.3, 42.1, 37.3, 35.1, 39.1, 37.3, 33~
## $ multiversions       &lt;chr&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA~
## $ tracking            &lt;lgl&gt; NA, TRUE, TRUE, TRUE, TRUE, NA, NA, TRUE, NA, TRUE~
## $ url                 &lt;chr&gt; &quot;https://docs.cdn.yougov.com/460mactkmh/econTabRep~
## $ poll_id             &lt;dbl&gt; 74332, 74338, 74366, 74347, 74367, 74345, 74348, 7~
## $ question_id         &lt;dbl&gt; 139593, 139642, 139733, 139654, 139734, 139652, 13~
## $ createddate         &lt;chr&gt; &quot;2/3/2021&quot;, &quot;2/4/2021&quot;, &quot;2/11/2021&quot;, &quot;2/5/2021&quot;, &quot;~
## $ timestamp           &lt;chr&gt; &quot;13:01:54 17 Sep 2021&quot;, &quot;13:01:54 17 Sep 2021&quot;, &quot;1~</code></pre>
<pre class="r"><code>library(lubridate) 

clean_approval_polllist &lt;- approval_polllist %&gt;%
  mutate(enddate=mdy(enddate),
         week=isoweek(enddate)) 

# Use `lubridate` to fix dates, as they are given as characters.</code></pre>
<div id="create-a-plot" class="section level2">
<h2>3.1. Create a plot</h2>
<p>What I would like you to do is to calculate the average net approval rate (approve- disapprove) for each week since he got into office. I want you plot the net approval, along with its 95% confidence interval. There are various dates given for each poll, please use <code>enddate</code>, i.e., the date the poll ended.</p>
<p>Also, please add an orange line at zero. Your plot should look like this:</p>
<p><img src="C:/Users/apple/Desktop/my_website/images/biden_approval_margin.png" width="100%" style="display: block; margin: auto;" /></p>
<pre class="r"><code>clean_approval_polllist &lt;- clean_approval_polllist %&gt;%
  filter(subgroup == &quot;Adults&quot;) %&gt;%
  mutate(daily_approval_margin = approve - disapprove)</code></pre>
<pre class="r"><code>weekly_avg_app_rates &lt;- clean_approval_polllist %&gt;%
  group_by(week) %&gt;%
  summarize( mean_weekly_approval_margin = mean(daily_approval_margin, na.rm = TRUE),
             number_polls = n(),
             std_weekly_approval_margin = STDEV(daily_approval_margin)) %&gt;%

  mutate(lower_bound_CI_app_rate = mean_weekly_approval_margin - qt(0.975, df=number_polls-1)*std_weekly_approval_margin/sqrt(number_polls),
         upper_bound_CI_app_rate = mean_weekly_approval_margin + qt(0.975, df=number_polls-1)*std_weekly_approval_margin/sqrt(number_polls))</code></pre>
<pre class="r"><code>qt(0.975,6)</code></pre>
<pre><code>## [1] 2.45</code></pre>
<pre class="r"><code>ggplot(weekly_avg_app_rates, aes(x=week)) +
  geom_point(aes(y=mean_weekly_approval_margin, color=&quot;red&quot;)) +
  geom_line( aes(y=mean_weekly_approval_margin, color=&quot;red&quot;)) +
  geom_ribbon(aes(ymin = lower_bound_CI_app_rate, 
                 ymax = upper_bound_CI_app_rate), 
                 show.legend = NA,
                 fill = &quot;grey&quot;,
                 colour = &quot;orange&quot;, 
                 alpha = 0.5) +
  geom_smooth(aes(y= mean_weekly_approval_margin), fill=NA)+
  geom_hline(yintercept=0, color=&quot;orange&quot;, size=3)+
  theme_bw() +
  labs (
    title = &quot;Estimating Approval Margin (Approve - Disapprove) for Joe Biden&quot;,
    subtitle = &quot;Weekly average of all polls&quot;,
    x = &quot;Week of the year&quot;,
    y = &quot;Average Approval Margin (Approve - Disapprove)&quot;
  ) +
  theme(legend.position = &quot;none&quot;)</code></pre>
<p><img src="/blogs/homework2_Group8_chuhan_files/figure-html/unnamed-chunk-17-1.png" width="648" style="display: block; margin: auto;" /></p>
</div>
<div id="compare-confidence-intervals" class="section level2">
<h2>3.2. Compare Confidence Intervals</h2>
<p>Compare the confidence intervals for <code>week 3</code> and <code>week 25</code>. Can you explain what’s going on? One paragraph would be enough.</p>
</div>
</div>
<div id="gapminder-revisited" class="section level1">
<h1>4. Gapminder revisited</h1>
<p>Recall the <code>gapminder</code> data frame from the gapminder package. That data frame contains just six columns from the larger <a href="https://www.gapminder.org/data/">data in Gapminder World</a>. In this part, we will join a few dataframes with more data than the ‘gapminder’ package. Specifically, we will look at data on</p>
<ul>
<li>Life expectancy at birth (life_expectancy_years.csv)</li>
<li>GDP per capita in constant 2010 US$ (<a href="https://data.worldbank.org/indicator/NY.GDP.PCAP.KD" class="uri">https://data.worldbank.org/indicator/NY.GDP.PCAP.KD</a>)</li>
<li>Female fertility: The number of babies per woman (<a href="https://data.worldbank.org/indicator/SP.DYN.TFRT.IN" class="uri">https://data.worldbank.org/indicator/SP.DYN.TFRT.IN</a>)</li>
<li>Primary school enrollment as % of children attending primary school (<a href="https://data.worldbank.org/indicator/SE.PRM.NENR" class="uri">https://data.worldbank.org/indicator/SE.PRM.NENR</a>)</li>
<li>Mortality rate, for under 5, per 1000 live births (<a href="https://data.worldbank.org/indicator/SH.DYN.MORT" class="uri">https://data.worldbank.org/indicator/SH.DYN.MORT</a>)</li>
<li>HIV prevalence (adults_with_hiv_percent_age_15_49.csv): The estimated number of people living with HIV per 100 population of age group 15-49.</li>
</ul>
<p>We have to use the <code>wbstats</code> package to download data from the World Bank. The relevant World Bank indicators are <code>SP.DYN.TFRT.IN</code>, <code>SE.PRM.NENR</code>, <code>NY.GDP.PCAP.KD</code>, and <code>SH.DYN.MORT</code></p>
<pre class="r"><code># load gapminder HIV data
hiv &lt;- read_csv(here::here(&quot;data&quot;,&quot;adults_with_hiv_percent_age_15_49.csv&quot;))
life_expectancy &lt;- read_csv(here::here(&quot;data&quot;,&quot;life_expectancy_years.csv&quot;))

# get World bank data using wbstats
indicators &lt;- c(&quot;SP.DYN.TFRT.IN&quot;,&quot;SE.PRM.NENR&quot;, &quot;SH.DYN.MORT&quot;, &quot;NY.GDP.PCAP.KD&quot;)


library(wbstats)

worldbank_data &lt;- wb_data(country=&quot;countries_only&quot;, #countries only- no aggregates like Latin America, Europe, etc.
                          indicator = indicators, 
                          start_date = 1960, 
                          end_date = 2016)

# get a dataframe of information regarding countries, indicators, sources, regions, indicator topics, lending types, income levels,  from the World Bank API 
countries &lt;-  wbstats::wb_cachelist$countries</code></pre>
<p>We have to join the 3 dataframes (life_expectancy, worldbank_data, and HIV) into one. We may need to tidy your data first and then perform <a href="http://r4ds.had.co.nz/relational-data.html">join operations</a>.</p>
<ol style="list-style-type: decimal">
<li>What is the relationship between HIV prevalence and life expectancy? We generate a scatterplot with a smoothing line to report our results.</li>
</ol>
<pre class="r"><code>skim(hiv)</code></pre>
<table>
<caption><span id="tab:unnamed-chunk-18">Table 1: </span>Data summary</caption>
<tbody>
<tr class="odd">
<td align="left">Name</td>
<td align="left">hiv</td>
</tr>
<tr class="even">
<td align="left">Number of rows</td>
<td align="left">154</td>
</tr>
<tr class="odd">
<td align="left">Number of columns</td>
<td align="left">34</td>
</tr>
<tr class="even">
<td align="left">_______________________</td>
<td align="left"></td>
</tr>
<tr class="odd">
<td align="left">Column type frequency:</td>
<td align="left"></td>
</tr>
<tr class="even">
<td align="left">character</td>
<td align="left">1</td>
</tr>
<tr class="odd">
<td align="left">logical</td>
<td align="left">2</td>
</tr>
<tr class="even">
<td align="left">numeric</td>
<td align="left">31</td>
</tr>
<tr class="odd">
<td align="left">________________________</td>
<td align="left"></td>
</tr>
<tr class="even">
<td align="left">Group variables</td>
<td align="left">None</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: character</strong></p>
<table>
<thead>
<tr class="header">
<th align="left">skim_variable</th>
<th align="right">n_missing</th>
<th align="right">complete_rate</th>
<th align="right">min</th>
<th align="right">max</th>
<th align="right">empty</th>
<th align="right">n_unique</th>
<th align="right">whitespace</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">country</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">3</td>
<td align="right">24</td>
<td align="right">0</td>
<td align="right">154</td>
<td align="right">0</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: logical</strong></p>
<table>
<thead>
<tr class="header">
<th align="left">skim_variable</th>
<th align="right">n_missing</th>
<th align="right">complete_rate</th>
<th align="right">mean</th>
<th align="left">count</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">1988</td>
<td align="right">154</td>
<td align="right">0</td>
<td align="right">NaN</td>
<td align="left">:</td>
</tr>
<tr class="even">
<td align="left">1989</td>
<td align="right">154</td>
<td align="right">0</td>
<td align="right">NaN</td>
<td align="left">:</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: numeric</strong></p>
<table>
<thead>
<tr class="header">
<th align="left">skim_variable</th>
<th align="right">n_missing</th>
<th align="right">complete_rate</th>
<th align="right">mean</th>
<th align="right">sd</th>
<th align="right">p0</th>
<th align="right">p25</th>
<th align="right">p50</th>
<th align="right">p75</th>
<th align="right">p100</th>
<th align="left">hist</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">1979</td>
<td align="right">107</td>
<td align="right">0.31</td>
<td align="right">0.03</td>
<td align="right">0.04</td>
<td align="right">0.01</td>
<td align="right">0.01</td>
<td align="right">0.02</td>
<td align="right">0.04</td>
<td align="right">0.16</td>
<td align="left">▇▁▁▁▁</td>
</tr>
<tr class="even">
<td align="left">1980</td>
<td align="right">151</td>
<td align="right">0.02</td>
<td align="right">0.01</td>
<td align="right">0.00</td>
<td align="right">0.01</td>
<td align="right">0.01</td>
<td align="right">0.01</td>
<td align="right">0.01</td>
<td align="right">0.02</td>
<td align="left">▇▁▁▁▃</td>
</tr>
<tr class="odd">
<td align="left">1981</td>
<td align="right">149</td>
<td align="right">0.03</td>
<td align="right">0.01</td>
<td align="right">0.00</td>
<td align="right">0.01</td>
<td align="right">0.01</td>
<td align="right">0.01</td>
<td align="right">0.01</td>
<td align="right">0.02</td>
<td align="left">▇▁▁▂▂</td>
</tr>
<tr class="even">
<td align="left">1982</td>
<td align="right">146</td>
<td align="right">0.05</td>
<td align="right">0.01</td>
<td align="right">0.00</td>
<td align="right">0.01</td>
<td align="right">0.01</td>
<td align="right">0.01</td>
<td align="right">0.01</td>
<td align="right">0.02</td>
<td align="left">▇▃▁▁▂</td>
</tr>
<tr class="odd">
<td align="left">1983</td>
<td align="right">146</td>
<td align="right">0.05</td>
<td align="right">0.01</td>
<td align="right">0.00</td>
<td align="right">0.01</td>
<td align="right">0.01</td>
<td align="right">0.01</td>
<td align="right">0.02</td>
<td align="right">0.02</td>
<td align="left">▇▅▂▁▅</td>
</tr>
<tr class="even">
<td align="left">1984</td>
<td align="right">151</td>
<td align="right">0.02</td>
<td align="right">0.01</td>
<td align="right">0.00</td>
<td align="right">0.01</td>
<td align="right">0.01</td>
<td align="right">0.01</td>
<td align="right">0.01</td>
<td align="right">0.01</td>
<td align="left">▃▁▁▁▇</td>
</tr>
<tr class="odd">
<td align="left">1985</td>
<td align="right">144</td>
<td align="right">0.06</td>
<td align="right">0.01</td>
<td align="right">0.01</td>
<td align="right">0.01</td>
<td align="right">0.01</td>
<td align="right">0.01</td>
<td align="right">0.01</td>
<td align="right">0.05</td>
<td align="left">▇▁▁▁▁</td>
</tr>
<tr class="even">
<td align="left">1986</td>
<td align="right">152</td>
<td align="right">0.01</td>
<td align="right">0.01</td>
<td align="right">0.00</td>
<td align="right">0.01</td>
<td align="right">0.01</td>
<td align="right">0.01</td>
<td align="right">0.01</td>
<td align="right">0.01</td>
<td align="left">▇▁▁▁▇</td>
</tr>
<tr class="odd">
<td align="left">1987</td>
<td align="right">151</td>
<td align="right">0.02</td>
<td align="right">0.01</td>
<td align="right">0.00</td>
<td align="right">0.01</td>
<td align="right">0.01</td>
<td align="right">0.01</td>
<td align="right">0.01</td>
<td align="right">0.01</td>
<td align="left">▇▁▁▁▃</td>
</tr>
<tr class="even">
<td align="left">1990</td>
<td align="right">8</td>
<td align="right">0.95</td>
<td align="right">0.80</td>
<td align="right">1.91</td>
<td align="right">0.06</td>
<td align="right">0.06</td>
<td align="right">0.10</td>
<td align="right">0.40</td>
<td align="right">12.70</td>
<td align="left">▇▁▁▁▁</td>
</tr>
<tr class="odd">
<td align="left">1991</td>
<td align="right">8</td>
<td align="right">0.95</td>
<td align="right">0.96</td>
<td align="right">2.22</td>
<td align="right">0.06</td>
<td align="right">0.06</td>
<td align="right">0.10</td>
<td align="right">0.50</td>
<td align="right">13.60</td>
<td align="left">▇▁▁▁▁</td>
</tr>
<tr class="even">
<td align="left">1992</td>
<td align="right">8</td>
<td align="right">0.95</td>
<td align="right">1.13</td>
<td align="right">2.55</td>
<td align="right">0.06</td>
<td align="right">0.06</td>
<td align="right">0.10</td>
<td align="right">0.67</td>
<td align="right">17.20</td>
<td align="left">▇▁▁▁▁</td>
</tr>
<tr class="odd">
<td align="left">1993</td>
<td align="right">8</td>
<td align="right">0.95</td>
<td align="right">1.32</td>
<td align="right">2.92</td>
<td align="right">0.06</td>
<td align="right">0.06</td>
<td align="right">0.10</td>
<td align="right">0.88</td>
<td align="right">20.60</td>
<td align="left">▇▁▁▁▁</td>
</tr>
<tr class="even">
<td align="left">1994</td>
<td align="right">8</td>
<td align="right">0.95</td>
<td align="right">1.51</td>
<td align="right">3.30</td>
<td align="right">0.06</td>
<td align="right">0.06</td>
<td align="right">0.10</td>
<td align="right">1.25</td>
<td align="right">23.30</td>
<td align="left">▇▁▁▁▁</td>
</tr>
<tr class="odd">
<td align="left">1995</td>
<td align="right">8</td>
<td align="right">0.95</td>
<td align="right">1.68</td>
<td align="right">3.68</td>
<td align="right">0.06</td>
<td align="right">0.06</td>
<td align="right">0.20</td>
<td align="right">1.48</td>
<td align="right">25.10</td>
<td align="left">▇▁▁▁▁</td>
</tr>
<tr class="even">
<td align="left">1996</td>
<td align="right">8</td>
<td align="right">0.95</td>
<td align="right">1.82</td>
<td align="right">4.04</td>
<td align="right">0.06</td>
<td align="right">0.06</td>
<td align="right">0.20</td>
<td align="right">1.48</td>
<td align="right">26.20</td>
<td align="left">▇▁▁▁▁</td>
</tr>
<tr class="odd">
<td align="left">1997</td>
<td align="right">8</td>
<td align="right">0.95</td>
<td align="right">1.93</td>
<td align="right">4.33</td>
<td align="right">0.06</td>
<td align="right">0.10</td>
<td align="right">0.20</td>
<td align="right">1.40</td>
<td align="right">26.50</td>
<td align="left">▇▁▁▁▁</td>
</tr>
<tr class="even">
<td align="left">1998</td>
<td align="right">8</td>
<td align="right">0.95</td>
<td align="right">2.02</td>
<td align="right">4.55</td>
<td align="right">0.06</td>
<td align="right">0.10</td>
<td align="right">0.30</td>
<td align="right">1.40</td>
<td align="right">26.30</td>
<td align="left">▇▁▁▁▁</td>
</tr>
<tr class="odd">
<td align="left">1999</td>
<td align="right">8</td>
<td align="right">0.95</td>
<td align="right">2.07</td>
<td align="right">4.69</td>
<td align="right">0.06</td>
<td align="right">0.10</td>
<td align="right">0.30</td>
<td align="right">1.48</td>
<td align="right">25.70</td>
<td align="left">▇▁▁▁▁</td>
</tr>
<tr class="even">
<td align="left">2000</td>
<td align="right">8</td>
<td align="right">0.95</td>
<td align="right">2.10</td>
<td align="right">4.77</td>
<td align="right">0.06</td>
<td align="right">0.10</td>
<td align="right">0.30</td>
<td align="right">1.48</td>
<td align="right">26.00</td>
<td align="left">▇▁▁▁▁</td>
</tr>
<tr class="odd">
<td align="left">2001</td>
<td align="right">8</td>
<td align="right">0.95</td>
<td align="right">2.11</td>
<td align="right">4.80</td>
<td align="right">0.06</td>
<td align="right">0.10</td>
<td align="right">0.40</td>
<td align="right">1.40</td>
<td align="right">26.30</td>
<td align="left">▇▁▁▁▁</td>
</tr>
<tr class="even">
<td align="left">2002</td>
<td align="right">8</td>
<td align="right">0.95</td>
<td align="right">2.09</td>
<td align="right">4.79</td>
<td align="right">0.06</td>
<td align="right">0.10</td>
<td align="right">0.40</td>
<td align="right">1.37</td>
<td align="right">26.30</td>
<td align="left">▇▁▁▁▁</td>
</tr>
<tr class="odd">
<td align="left">2003</td>
<td align="right">8</td>
<td align="right">0.95</td>
<td align="right">2.08</td>
<td align="right">4.74</td>
<td align="right">0.06</td>
<td align="right">0.10</td>
<td align="right">0.40</td>
<td align="right">1.30</td>
<td align="right">26.10</td>
<td align="left">▇▁▁▁▁</td>
</tr>
<tr class="even">
<td align="left">2004</td>
<td align="right">8</td>
<td align="right">0.95</td>
<td align="right">2.06</td>
<td align="right">4.67</td>
<td align="right">0.06</td>
<td align="right">0.10</td>
<td align="right">0.40</td>
<td align="right">1.30</td>
<td align="right">25.80</td>
<td align="left">▇▁▁▁▁</td>
</tr>
<tr class="odd">
<td align="left">2005</td>
<td align="right">8</td>
<td align="right">0.95</td>
<td align="right">2.03</td>
<td align="right">4.60</td>
<td align="right">0.06</td>
<td align="right">0.10</td>
<td align="right">0.40</td>
<td align="right">1.30</td>
<td align="right">25.60</td>
<td align="left">▇▁▁▁▁</td>
</tr>
<tr class="even">
<td align="left">2006</td>
<td align="right">8</td>
<td align="right">0.95</td>
<td align="right">2.00</td>
<td align="right">4.53</td>
<td align="right">0.06</td>
<td align="right">0.10</td>
<td align="right">0.40</td>
<td align="right">1.37</td>
<td align="right">25.70</td>
<td align="left">▇▁▁▁▁</td>
</tr>
<tr class="odd">
<td align="left">2007</td>
<td align="right">8</td>
<td align="right">0.95</td>
<td align="right">1.98</td>
<td align="right">4.47</td>
<td align="right">0.06</td>
<td align="right">0.10</td>
<td align="right">0.40</td>
<td align="right">1.37</td>
<td align="right">25.80</td>
<td align="left">▇▁▁▁▁</td>
</tr>
<tr class="even">
<td align="left">2008</td>
<td align="right">8</td>
<td align="right">0.95</td>
<td align="right">1.96</td>
<td align="right">4.43</td>
<td align="right">0.06</td>
<td align="right">0.10</td>
<td align="right">0.40</td>
<td align="right">1.30</td>
<td align="right">25.90</td>
<td align="left">▇▁▁▁▁</td>
</tr>
<tr class="odd">
<td align="left">2009</td>
<td align="right">8</td>
<td align="right">0.95</td>
<td align="right">1.93</td>
<td align="right">4.34</td>
<td align="right">0.06</td>
<td align="right">0.20</td>
<td align="right">0.40</td>
<td align="right">1.30</td>
<td align="right">25.80</td>
<td align="left">▇▁▁▁▁</td>
</tr>
<tr class="even">
<td align="left">2010</td>
<td align="right">9</td>
<td align="right">0.94</td>
<td align="right">1.93</td>
<td align="right">4.33</td>
<td align="right">0.06</td>
<td align="right">0.20</td>
<td align="right">0.40</td>
<td align="right">1.30</td>
<td align="right">25.90</td>
<td align="left">▇▁▁▁▁</td>
</tr>
<tr class="odd">
<td align="left">2011</td>
<td align="right">7</td>
<td align="right">0.95</td>
<td align="right">1.91</td>
<td align="right">4.28</td>
<td align="right">0.06</td>
<td align="right">0.20</td>
<td align="right">0.40</td>
<td align="right">1.30</td>
<td align="right">26.00</td>
<td align="left">▇▁▁▁▁</td>
</tr>
</tbody>
</table>
<pre class="r"><code>life_expectency_long &lt;- life_expectancy %&gt;%
  pivot_longer(2:302, values_to = &quot;life_expec&quot; , names_to = &quot;year&quot;)

hiv_long &lt;- hiv %&gt;%
  pivot_longer(2:34, values_to = &quot;prop_hiv&quot; , names_to = &quot;year&quot;)

life_hiv &lt;- right_join(hiv_long, life_expectency_long, by = c(&quot;year&quot; = &quot;year&quot;, &quot;country&quot; = &quot;country&quot;))

life_hiv$year = as.numeric(life_hiv$year)

life_hiv_bank_data &lt;- left_join(life_hiv, worldbank_data, by = c(&quot;year&quot; = &quot;date&quot;, &quot;country&quot; = &quot;country&quot;))

life_hiv_bank_data &lt;- life_hiv_bank_data %&gt;%
  rename(fertilityRate = SP.DYN.TFRT.IN, gdp = NY.GDP.PCAP.KD, mortalityRate = SH.DYN.MORT, primarySchoolEnrolment = SE.PRM.NENR)</code></pre>
<p>We used a mixture of both right and left joins because so long as the dataframes are in the correct order when passed through the function, it does not matter whether you do a right or left join. We did not use an inner join as that would have resulted in data loss - the HIV dataframe only has values from the year 1979 onwards whereas the life expectancy dataframe has values from the year 1800 onwards.</p>
<pre class="r"><code>life_hiv_bank_data_region &lt;- right_join( life_hiv_bank_data ,countries, by = c( &quot;country&quot; = &quot;country&quot;)) %&gt;%
  select(year, country, region,fertilityRate, gdp, mortalityRate, primarySchoolEnrolment, prop_hiv,life_expec )</code></pre>
<ol style="list-style-type: decimal">
<li>What is the relationship between HIV prevalence and life expectancy? We generate a scatterplot with a smoothing line to report your results. You may find faceting useful</li>
</ol>
<pre class="r"><code>ggplot(life_hiv_bank_data_region, aes(x=prop_hiv, y=life_expec )) +
  geom_point() +
  scale_y_log10() +
  scale_x_log10() +
  ylim(30,100) +
  geom_smooth(method = &quot;lm&quot;, formula= y~x) +
  labs( title = &quot;Relationship HIV prevalence and life expectancy &quot;, y = &quot;Life Expectency&quot;, x = &quot;Proportion of HIV prevalance &quot;)</code></pre>
<p><img src="/blogs/homework2_Group8_chuhan_files/figure-html/unnamed-chunk-21-1.png" width="648" style="display: block; margin: auto;" /></p>
<p>As we can see from the above plot, as the proportion of HIV prevalence increases, the life expectancy decreases. Thus, there is a negative relationship between the two variables.</p>
<ol style="list-style-type: decimal">
<li>What is the relationship between fertility rate and GDP per capita? We generate a scatterplot with a smoothing line to report our results.</li>
</ol>
<pre class="r"><code>ggplot(life_hiv_bank_data_region, aes(x=fertilityRate , y=gdp )) +
  geom_point() +
  scale_y_log10() +
  scale_x_log10() +
#  ylim(30,100) +
  geom_smooth(method = &quot;lm&quot;, formula= y~x) +
  facet_wrap(~region) +
  labs( title = &quot;Relationship fertility rate and GDP per capita &quot;, y = &quot;GDP per capita&quot;, x = &quot;Fertility rate &quot;)</code></pre>
<p><img src="/blogs/homework2_Group8_chuhan_files/figure-html/unnamed-chunk-22-1.png" width="648" style="display: block; margin: auto;" /></p>
<p>As GDP increases, the fertility rate decreases.</p>
<ol style="list-style-type: decimal">
<li>Which regions have the most observations with missing HIV data? We generate a bar chart (<code>geom_col()</code>), in descending order.</li>
</ol>
<pre class="r"><code>NA_count &lt;- life_hiv_bank_data_region %&gt;%
  group_by(region) %&gt;%
  filter(is.na(prop_hiv)) %&gt;%
  summarise(countNA = n())</code></pre>
<pre class="r"><code>ggplot(NA_count,aes( y = fct_reorder(region, countNA), x = countNA)) +
  geom_col()</code></pre>
<p><img src="/blogs/homework2_Group8_chuhan_files/figure-html/unnamed-chunk-24-1.png" width="648" style="display: block; margin: auto;" /></p>
<p>Sub-Saharan Africa and Europe &amp; Central Asia have the most missing observations for HIV data.</p>
<ol style="list-style-type: decimal">
<li>How has mortality rate for under 5 changed by region? In each region, we find the top 5 countries that have seen the greatest improvement, as well as those 5 countries where mortality rates have had the least improvement or even deterioration.</li>
</ol>
<pre class="r"><code>mortality_diff &lt;- life_hiv_bank_data_region %&gt;%
  filter(year == 1800 | year == 2021 ) %&gt;%
  group_by(year) %&gt;%
  mutate( region = region, 
          country = country, 
          life_expec = life_expec) %&gt;%
  select(region, country, life_expec) %&gt;%
  pivot_wider( names_from = year, values_from = life_expec) %&gt;%
  rename(&quot;year_1800&quot; = &quot;1800&quot;, &quot;year_2021&quot;= &quot;2021&quot;) %&gt;%
  mutate(change_mortality = (year_2021 - year_1800) )</code></pre>
<pre class="r"><code>mortality_top5 &lt;- mortality_diff %&gt;%
  group_by(region) %&gt;%
  slice_max(order_by = change_mortality, n=5)

mortality_top5</code></pre>
<pre><code>## # A tibble: 32 x 5
## # Groups:   region [7]
##    region                country         year_1800 year_2021 change_mortality
##    &lt;chr&gt;                 &lt;chr&gt;               &lt;dbl&gt;     &lt;dbl&gt;            &lt;dbl&gt;
##  1 East Asia &amp; Pacific   Singapore            29.1      85.4             56.3
##  2 East Asia &amp; Pacific   Australia            34        83               49  
##  3 East Asia &amp; Pacific   Thailand             30.4      79               48.6
##  4 East Asia &amp; Pacific   Japan                36.4      84.8             48.4
##  5 East Asia &amp; Pacific   New Zealand          34        82.2             48.2
##  6 Europe &amp; Central Asia Italy                29.7      83.8             54.1
##  7 Europe &amp; Central Asia Spain                29.5      83.6             54.1
##  8 Europe &amp; Central Asia Sweden               32.2      83.1             50.9
##  9 Europe &amp; Central Asia Kyrgyz Republic      23.9      73.3             49.4
## 10 Europe &amp; Central Asia France               34        83.3             49.3
## # ... with 22 more rows</code></pre>
<pre class="r"><code>mortality_least5 &lt;- mortality_diff %&gt;%
  group_by(region) %&gt;%
  slice_max(order_by = -change_mortality, n=5)

mortality_least5</code></pre>
<pre><code>## # A tibble: 32 x 5
## # Groups:   region [7]
##    region                country          year_1800 year_2021 change_mortality
##    &lt;chr&gt;                 &lt;chr&gt;                &lt;dbl&gt;     &lt;dbl&gt;            &lt;dbl&gt;
##  1 East Asia &amp; Pacific   Papua New Guinea      31.5      59.3             27.8
##  2 East Asia &amp; Pacific   Cambodia              35        70.9             35.9
##  3 East Asia &amp; Pacific   Mongolia              31.8      69.7             37.9
##  4 East Asia &amp; Pacific   Kiribati              24.9      63.3             38.4
##  5 East Asia &amp; Pacific   Myanmar               30.8      69.5             38.7
##  6 Europe &amp; Central Asia Ukraine               36.6      71               34.4
##  7 Europe &amp; Central Asia Belarus               36.2      74.8             38.6
##  8 Europe &amp; Central Asia Bulgaria              35.8      75.4             39.6
##  9 Europe &amp; Central Asia Romania               35.7      75.7             40  
## 10 Europe &amp; Central Asia Moldova               33.1      73.3             40.2
## # ... with 22 more rows</code></pre>
<p>We can see that each region has seen various changes in mortality rate over the years.</p>
<ol style="list-style-type: decimal">
<li>Is there a relationship between primary school enrollment and fertility rate?</li>
</ol>
<pre class="r"><code>ggplot(life_hiv_bank_data_region, aes(x=primarySchoolEnrolment, y=fertilityRate)) +
  geom_point() +
  scale_x_log10() +
  scale_y_log10() + 
  geom_smooth(method = &quot;lm&quot;, formula = y~x)</code></pre>
<p><img src="/blogs/homework2_Group8_chuhan_files/figure-html/unnamed-chunk-27-1.png" width="648" style="display: block; margin: auto;" /></p>
<pre class="r"><code> life_hiv_bank_data_region %&gt;%
  select(fertilityRate, primarySchoolEnrolment) %&gt;%
  na.omit() %&gt;%
  cor()</code></pre>
<pre><code>##                        fertilityRate primarySchoolEnrolment
## fertilityRate                  1.000                 -0.727
## primarySchoolEnrolment        -0.727                  1.000</code></pre>
<p>As we can see from the scatter plot, there is a strong negative relationship between primary school enrollment and fertility rate. We can see that as primary school enrollment increases, the fertility rate decreases. This is further supported by the correlation between the two variables. The correlation in question is -0.727 which is quite significant negative correlation.</p>
</div>
<div id="challenge-1-excess-rentals-in-tfl-bike-sharing" class="section level1">
<h1>5. Challenge 1: Excess rentals in TfL bike sharing</h1>
<p>Recall the TfL data on how many bikes were hired every single day. We can get the latest data by running the following</p>
<pre class="r"><code>url &lt;- &quot;https://data.london.gov.uk/download/number-bicycle-hires/ac29363e-e0cb-47cc-a97a-e216d900a6b0/tfl-daily-cycle-hires.xlsx&quot;

# Download TFL data to temporary file
httr::GET(url, write_disk(bike.temp &lt;- tempfile(fileext = &quot;.xlsx&quot;)))</code></pre>
<pre><code>## Response [https://airdrive-secure.s3-eu-west-1.amazonaws.com/london/dataset/number-bicycle-hires/2021-08-23T14%3A32%3A29/tfl-daily-cycle-hires.xlsx?X-Amz-Algorithm=AWS4-HMAC-SHA256&amp;X-Amz-Credential=AKIAJJDIMAIVZJDICKHA%2F20210919%2Feu-west-1%2Fs3%2Faws4_request&amp;X-Amz-Date=20210919T103535Z&amp;X-Amz-Expires=300&amp;X-Amz-Signature=cfb7166b415f285cda8eeddb6234d155c88aad916d1d8cdc5bc728b679ff6f58&amp;X-Amz-SignedHeaders=host]
##   Date: 2021-09-19 10:35
##   Status: 200
##   Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet
##   Size: 173 kB
## &lt;ON DISK&gt;  C:\Users\apple\AppData\Local\Temp\RtmpmanwWo\file18d01895428f.xlsx</code></pre>
<pre class="r"><code># Use read_excel to read it as dataframe
bike0 &lt;- read_excel(bike.temp,
                   sheet = &quot;Data&quot;,
                   range = cell_cols(&quot;A:B&quot;))

# change dates to get year, month, and week
bike &lt;- bike0 %&gt;% 
  clean_names() %&gt;% 
  rename (bikes_hired = number_of_bicycle_hires) %&gt;% 
  mutate (year = year(day),
          month = lubridate::month(day, label = TRUE),
          week = isoweek(day))</code></pre>
<p>We can easily create a facet grid that plots bikes hired by month and year.</p>
<p><img src="C:/Users/apple/Desktop/my_website/images/tfl_distributions_monthly.png" width="100%" style="display: block; margin: auto;" /></p>
<p>We can see that in the month of May and June 2020, bike rentals went down immensely, compared to previous years. This can be attributed to the national lockdowns that were enforced due to the COVID-19 pandemic during that time.</p>
<p>We will recreate the following graph:</p>
<p><img src="C:/Users/apple/Desktop/my_website/images/tfl_monthly.png" width="100%" style="display: block; margin: auto;" /></p>
<pre class="r"><code> general_monthly_average &lt;- bike %&gt;% 
  filter(year&gt;=2016 &amp; year&lt;=2019) %&gt;% 
  group_by(month) %&gt;%
  summarise(general_monthly_average = mean(bikes_hired))

monthly_average &lt;- bike %&gt;% 
  filter(year&gt;=2016) %&gt;%
  group_by(year, month) %&gt;%
  summarise(monthly_average = mean(bikes_hired),
            year = unique(year))

full_monthly_averages &lt;- left_join(monthly_average, general_monthly_average, by=&quot;month&quot;)

full_monthly_averages %&gt;% 
  ggplot(aes(x=month, group=1)) +
  geom_line(aes(y=monthly_average)) +
  geom_line(aes(y=general_monthly_average),
            color = &quot;blue&quot;,
            size=0.8) +
  geom_ribbon(aes(ymin = ifelse(general_monthly_average &gt; monthly_average, general_monthly_average, monthly_average), 
                  ymax = general_monthly_average), 
              fill = &quot;palegreen3&quot;, 
              alpha = 0.5)+
  geom_ribbon(aes(ymin = ifelse(general_monthly_average &lt;= monthly_average, general_monthly_average, monthly_average), 
                  ymax = general_monthly_average), 
              fill = &quot;lightcoral&quot;, alpha = 0.5) +
  facet_wrap(~year)+
  labs(title = &quot;Monthly changes if Tfl bike rentals&quot;,
       subtitle=&quot;Change from monthly average shown in blue \nand calculated between 2026-2019&quot;,
       y = &quot;Bike rentals&quot;,
       x = &quot;Months&quot;
  ) +
  theme_minimal() +
  theme(
    axis.text.x = element_text(size = 6),
    axis.text.y = element_text(size = 6)
    ) +
  NULL</code></pre>
<p><img src="/blogs/homework2_Group8_chuhan_files/figure-html/unnamed-chunk-29-1.png" width="648" style="display: block; margin: auto;" /></p>
<p>The second one looks at percentage changes from the expected level of weekly rentals. The two grey shaded rectangles correspond to Q2 (weeks 14-26) and Q4 (weeks 40-52).</p>
<p><img src="C:/Users/apple/Desktop/my_website/images/tfl_weekly.png" width="100%" style="display: block; margin: auto;" /></p>
<pre class="r"><code>expected_bike_pw &lt;- bike %&gt;%
  filter(day &gt;= as.Date(&quot;2016-1-1&quot;) &amp; day &lt;= as.Date(&quot;2019-12-31&quot;)) %&gt;%
  group_by(week) %&gt;% 
  summarise(expected_rentals = mean(bikes_hired))

bike_pw &lt;- bike %&gt;%
  filter(year &gt;= 2016 &amp; !(year == 2021 &amp; week &gt; 30)) %&gt;%
  group_by(year, week) %&gt;% 
  summarise(actual_rentals = mean(bikes_hired)) %&gt;% 
  left_join(expected_bike_pw, by=&quot;week&quot;) %&gt;% 
  mutate(excess_rentals = actual_rentals - expected_rentals,
         excess_rentals_inpct = excess_rentals/expected_rentals)</code></pre>
<pre class="r"><code>weekly_plot &lt;- bike_pw %&gt;% 
  ggplot(aes(x = week)) +
  geom_line(aes(y = excess_rentals_inpct), 
            color = &quot;black&quot;, 
            size = 0.1) +
  geom_ribbon(aes(ymin = ifelse(excess_rentals_inpct &gt; 0, 0, excess_rentals_inpct), 
                  ymax = excess_rentals_inpct),
              fill = &quot;green4&quot;, alpha = 0.3) +
  geom_ribbon(aes(ymin = ifelse(excess_rentals_inpct &gt; 0, excess_rentals_inpct, 0), 
                  ymax = excess_rentals_inpct),
              fill = &quot;red&quot;, alpha = 0.3) +
  geom_rug(color = ifelse(bike_pw$excess_rentals_inpct &gt; 0 , &quot;green&quot;, &quot;red&quot;),
           alpha = 0.5,
           size = 0.3) +
  annotate(&quot;rect&quot;,xmin = 13, xmax = 26, ymin = -Inf, ymax = Inf, fill = &quot;grey&quot;, alpha = 0.3) +
  annotate(&quot;rect&quot;,xmin = 39, xmax = 53, ymin = -Inf, ymax = Inf, fill = &quot;grey&quot;, alpha = 0.3) +
  scale_y_continuous(labels = scales::percent) +
  scale_x_continuous(breaks = seq(13,53,by=13)) +
  facet_wrap(~year) +
  theme_minimal() +
  theme(plot.title = element_text(size=7, face=&quot;bold&quot;),
        plot.subtitle = element_text(size=6, face=&quot;bold&quot;),
        axis.text.y = element_text(size=5),
        axis.text.x = element_text(size=5),
        axis.title.x = element_text(size=5, face=&quot;bold&quot;),
        strip.text = element_text(size=5),
        plot.caption = element_text(size=5),
        panel.grid.major = element_line(size=0.1),
        panel.grid.minor = element_line(size=0.1)) +
  labs(title = &quot;Monthly changes in TfL bike rentals&quot;, 
       subtitle = &quot;% change from weekly averages \n calculated between 2016-2019&quot;,
       y = &quot;&quot;, 
       x = &quot;week&quot;,
       caption = &quot;Source: TfL, London Data Store&quot;) 
weekly_plot</code></pre>
<p><img src="/blogs/homework2_Group8_chuhan_files/figure-html/unnamed-chunk-31-1.png" width="960" style="display: block; margin: auto;" /></p>
<p>For both of these graphs, we to calculate the expected number of rentals per week or month between 2016-2019 and then, we see how each week/month of 2020-2021 compares to the expected rentals. Think of the calculation <code>excess_rentals = actual_rentals - expected_rentals</code>.</p>
<p>Note: We can see massive spikes in the previous graph, so it might be more useful to use the median rather than the mean, as extreme values won’t affect it as much.</p>
</div>
<div id="details" class="section level1">
<h1>6. Details</h1>
<ul>
<li>Who did you collaborate with: Chuhan Zhang, Anuhya Yallabandi, Estelle Tessaro, Francois Mizrahi, Zervaan Borok, Zhicong Hu</li>
<li>Approximately how much time did you spend on this problem set: A lot….</li>
<li>What, if anything, gave you the most trouble: the Biden exercice</li>
</ul>
</div>
